# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fa58976f4cacd2088f5668041c114f54f57cc162ad6a44bca89f60cb0d02f087a459672ac8b0cba550a7e5a64e6a83d632be34a78ad23ca805cca83a48ad7ff

test:
  secret_key_base: 74c62ee9d0c287a8be33f6a8c66b52b0db4b0e52ed0ea617cfb49ba2e81caa79c40919f95564a425998f34f058f2b4bc1c68a1c7a3cc1e2afe6bd9176989970e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
